
namespace GroupDocs.Editor.WebForms
{
    public partial class Startup {        
        public void Configuration() {
            // Action generated by the FrameWork - required for compilation
        }
    }
}
